### ISSUE TITLE
Reservation form 

### ISSUE THREAD

**Issue by mammut47** [Kuestenschmiede/ReservationBundle#32]
The Reservation form shows a message with "individual service life"?
But there is no field to fill. Not in Backend nor in Frontend.
![image](https://github.com/Kuestenschmiede/ReservationBundle/assets/12047148/b72cb6af-b85e-4f40-a6e9-1a3e10091642)
Contao: 4.13
PHP: 8.2

**Comment by mammut47** [comment]
If in "Reservation Type" the "Minimum Period of use" and the "Maximum Period of use" is on the same Period (and not 0) than this Message appear. If both are zero, this message dissappears

**Comment by Tomatenmarc22** [comment]
Hello mammut47,

this message appears since having both min and max individual duration set to the same value, like 1 for instance, will stop the field from being displayed in the Front end.

That is why using any number, that is not the same, will allow the duration field to be displayed.

**With a Min and Max:**

![image](https://github.com/Kuestenschmiede/ReservationBundle/assets/111575074/5a5b8be4-5479-4cc3-9c66-d3e456fc23f6)

**The Backend**

![image](https://github.com/Kuestenschmiede/ReservationBundle/assets/111575074/f10d5a1d-20b3-4ba4-9797-41d93e51ac91)

**The Frontend**



Best Regards
Marc
